resource "aws_cloudwatch_dashboard" "dashboard" {

    dashboard_name = "test_dashboard"
    dashboard_body = <<EOF
      {
   "widgets":[
      {
         "type":"explorer",
         "x":0,
         "y":0,
         "width":24,
         "height":15,
         "properties":{
            "metrics":[
               {
                  "metricName":"CPUUtilization",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Average"
               },
               {
                  "metricName":"DiskReadBytes",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Average"
               },
               {
                  "metricName":"DiskReadOps",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Average"
               },
               {
                  "metricName":"DiskWriteBytes",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Average"
               },
                {
                  "metricName":"DiskWriteOps",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Average"
               },
               {
                  "metricName":"NetworkIn",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Average"
               },
               {
                  "metricName":"NetworkOut",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Average"
               },
               {
                  "metricName":"NetworkPacketsIn",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Average"
               },
               {
                  "metricName":"NetworkPacketsOut",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Average"
               },
               {
                  "metricName":"StatusCheckFailed",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Sum"
               },
               {
                  "metricName":"StatusCheckFailed_Instance",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Sum"
               },
               {
                  "metricName":"StatusCheckFailed_System",
                  "resourceType":"AWS::EC2::Instance",
                  "stat":"Sum"
               }
            ],
            "labels":[
               {
                  "key":"Name"
               }
            ],
            "aggregateBy":{
               "func":"AVG",
               "key":"AvailabilityZone"
            },
            "splitBy":"InstanceType",
            "widgetOptions":{
               "legend":{
                  "position":"bottom"
               },
               "view":"timeSeries",
               "stacked":false,
               "rowsPerPage":50,
               "widgetsPerRow":2
            },
            "period":300,
            "region":"ap-south-1",
            "title":""
         }
      }
   ]
}
  EOF
}
